[package]
name = "grpc-rust"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stargate-grpc = "0.3"
tokio = { version = "1", features = ["full"]}